# This template merge config file lists:
#
# - name: name of template stuff
# - patterns: strings to do text substitution on
# - rev_id: a sequential revision id of the template repo (manually maintained for now)
# - required: a full list of all files always merged
# - optional: a full list of all files merged when the --optional flag is used with `gut template`
# - ignored: never used in merging, only when populating new repos

name = "Shared Template"
patterns = ["__UND__", "__UNDEFINED__"]
rev_id = 4
required = [".gitignore",
            ".github/workflows/docs.yml",
            "Makefile.am",
            "autogen.sh",
            "configure.ac",
            "docs/_config.yml",
            "giella-shared-__UND__.pc.in",
            "src/Makefile.am",
            "src/fst/Makefile.am",
            "src/fst/stems/Makefile.am"]

optional = ["README.md",
            "docs/index.md",
            "src/fst/stems/__UND__-propernouns.lexc"]

ignored  = ["LICENSE",
            ".gut/delta.toml"]
